from .base_actor import BaseActor
from .fcot_online_reg_actor import FcotOnlineRegressionActor
from .fcot_cls_72_and_reg_init_actor import FcotCls72AndRegInitActor
from .fcot_cls_18_actor import FcotCls18Actor
from .fcot_actor import FcotActor